### PR TITLE
Added support for persistent profiles

### PR DESCRIPTION
**Pull request by pauliainbrooks**

### CODE REVIEW

**Comment by kkapsner** [comment]
Thank you for your contribution.
Please provide information why you want persistent profiles. I see no point in adding them.

PS: Also please make sure the your code style is consistent with the existing one. I will not accept greek letters in attribute names.
PPS: I do not quite get why you want to have different seeds for different canvas contents. And if you really need it: there is a much faster way to create a string from a canvas - toDataURL().

**Comment by pauliainbrooks** [comment]
Many thanks for the response to the pull request. CanvasBlocker is a really useful plugin.

I think persistent profiles are useful for several reasons:

1. User experience on web sites which expect a consistent canvas fingerprint. Web sites expect the canvas fingerprint to be consistent, and so may use the canvas hash to contribute to a key for maintaining server side user data. If the canvas changes each time it is requested, then this can lead to unexpected results in their delivery of content.

2. Canvas detection. If the canvas changes each time then it is trivial to detect the use of this technique. You just request two identical canvases and compare them. By having a consistent seed driving deterministic noise generation then repeated requests for the same canvas produce the same results.

The persistent profile functionality is optional and switched off by default - so as it stands it doesn't have any impact on existing functionality.

The reason for using different seeds per canvas is to avoid the problem of a website requesting a canvas which has no anti-alias/font hinting artifacts and using that to determine the PRNG sequence, and then using that to undo the noise added on subsequent canvases. By mixing the canvas content into each request we have a deterministic PRNG, but one which doesn't reveal anything about the profile seed. Good idea about the use of toDataURL() - hadn't thought of that. I'll update accordingly.

With regard to code style - I'm happy to update to make it consistent. If you would like to incorporate the persistent profile functionality then let me know and I'll do the updates to the code.

Thanks

Paul

**Comment by kkapsner** [comment]
Do you have an example website for your first point? I don't think that any website does this as there are way easier methods to identify visitors if only one website is involved (and they are not able to identify people but computers... no good thing for real content in my opinion). And if someone really needs the right content that such a website they should whiltelist it. So your first point does not convince me.

Your second point is not valid. Unfortunately it will always be possible to detect the usage of faked image data. Just draw a rectangle with a plain color (e.g. white) on a canvas (https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/rect) and check if the returned pixels all have the expected value. If not the data is faked.

**Comment by pauliainbrooks** [comment]
You're right. Users could disable the plugin for specific websites if they encounter an unusual user experience. I also agree that websites will defer to using the range of cookie methods to identify a returning identity, and the canvas fingerprint will only form part of an ultimate calculation of a connecting device/user. The reason I thought persistent profiles might provide a useful function is that for many people, the anonymity they seek is probably coupled to a session, or activity - one which involves multiple exchanges with a website. A constantly changing canvas fingerprint is not normal, and if the trend in take-up of canvas fingerprinting continues, then this will probably start to have some adverse impact on user experience. I couldn't find any examples of websites which demonstrate this - so I guess I'm just thinking ahead:) For what it's worth, one of the alternative Firefox plugins (MultiLoginApp's) creates a persistent profile for just this reason. Unfortunately, their plugin appears to hook the draw operations rather than Canvas export operations  - so suffers horribly from performance issues.

On the second point. While I agree it will always be possible to detect a faked canvas in the extreme, I do think it's worth exploring ways of stopping the easy cases. It's the next step in this battle between privacy invading techniques and the controls we use to disrupt them. Any combination of drawing operations which don't introduce anti-alias or font hinting artifacts could be used for the trivial test you describe. If you are interested, I do have some code which detects trivial canvas content and bypasses the noise addition. I was also having a play with edge detection, as I thought this might become useful at some point in the future.

Cheers
Paul

**Comment by kkapsner** [comment]
Hm... I agree that a constant return value for a canvas within the same session and domain has some advantages. But on different domains the return value should be different. Similar to the SOP - only the same origin can get the same value.

I also do not like the need to carry a prng within the code base. I will dig into the Firefox APIs - maybe I find something we can use.

**Comment by pauliainbrooks** [comment]
If you wanted to have a consistent canvas fingerprint on a per domain basis, then we could just mix the domain name into the PRNG seed.

I'll have a poke around for a PRNG in the Firefox API as well. I was surprised that I couldn't seed the existing Javascript one, but apparently this is a known limitation.

**Comment by TPS** [comment]
#64's fix handles this, I think, so probably this PR is now irrelevant?

**Comment by kkapsner** [comment]
Not irrelevant because the persistent module can still need some improvements.

**Pull request closed without merging**
