### PR TITLE
Update description.txt

### PR DESCRIPTION
**Pull request by joaonsg**
fixed typo

### CODE REVIEW

**Comment by kkapsner** [comment]
Thanks.

**Comment by spodermenpls** [comment]
The same mistake is in the "README.md" file.

**Comment by spodermenpls** [comment]
@kkapsner The same mistake is in the "README.md" file.

**Comment by kkapsner** [comment]
Thanks for the input.
@joaonsg: sorry, but due to some local git confusion I had to overwrite your merge request... but you are acknowledged in the commit message.

**Pull request merged**
